GET http://localhost:2000/todos/?status=TO%20DO

###

GET http://localhost:2000/todos/?priority=LOW

###

GET http://localhost:2000/todos/?status=TO%20DO&priority=HIGH

###

GET http://localhost:2000/todos/?search_q=Play

###
GET http://localhost:2000/todos/2/

###

POST http://localhost:2000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

###

PUT http://localhost:2000/todos/2
Content-Type: application/json

{ "priority": "HIGH" }